"""Regenerate the deterministic demo mods (10 phases) into ``mods/.test1``.

Runs the full LangGraph pipeline (route -> generate -> T1 gate -> T2 gate
-> package) for each demo prompt with no LLM keys configured, so every
generator falls back to its deterministic data. Mirrors the structure of
``mods/.test``: flat zips in ``mods/``, extracted contents in
``extracted/``, plus a generated README.md.

Usage:
    python scripts/demo_generate.py            # regenerate all 10 phases
    python scripts/demo_generate.py --phase achievements   # one phase
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import shutil
import sys
import zipfile
from pathlib import Path

# Make the package importable when run as ``python scripts/demo_generate.py``.
_PKG_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PKG_DIR))

# Deterministic generation: never let a stray LLM key be used.
os.environ.pop("OPENAI_API_KEY", None)
os.environ.pop("ANTHROPIC_API_KEY", None)

_TARGET = _PKG_DIR.parent / "mods" / ".test1"
_LOCAL_OUTPUT_DIR = _TARGET / "outputs"
os.environ["LOCAL_OUTPUT_DIR"] = str(_LOCAL_OUTPUT_DIR)

DEMO_PROMPTS: list[tuple[str, str]] = [
    ("shop_channel", "make a TV shopping channel that sells rare seeds every Sunday"),
    ("texture", "replace the parsnip crop sprite with a golden glowing version"),
    ("npc_schedule", "give the NPC Linus a new daily schedule and dialogue lines"),
    ("event_mod", "add a spring flower festival event in the town square"),
    ("custom_crafting", "add a new custom crafting recipe for a magical fertilizer"),
    ("farm_expansion", "add a farm expansion building with a warp point to the beach"),
    ("weather_event", "add a rain storm weather event that grants a buff"),
    ("achievements", "add an achievement for harvesting 100 ancient fruit"),
    ("weapon_definition", "add a custom sword weapon with high damage"),
    ("tool_definition", "add a custom pickaxe tool with faster mining speed"),
]


async def run_one(phase: str, prompt: str) -> dict:
    from orchestrator.pipeline import run_pipeline

    request_id = f"demo_{phase}"
    result = await run_pipeline(request_id, "demo", prompt)

    summary = {
        "phase": phase,
        "prompt": prompt,
        "request_id": request_id,
        "status": result.status,
        "t1_passed": result.t1_passed,
        "t2_passed": result.t2_passed,
        "t2_available": result.t2_available,
        "t2_score": result.t2_score,
        "zip_key": result.zip_key,
        "generators_succeeded": result.generators_succeeded,
        "generators_failed": result.generators_failed,
        "errors": result.errors,
    }
    return summary


def copy_artifact(summary: dict) -> None:
    phase = summary["phase"]
    request_id = summary["request_id"]
    zip_path = _LOCAL_OUTPUT_DIR / "mods" / request_id / f"{request_id}.zip"

    mods_dir = _TARGET / "mods"
    extracted_dir = _TARGET / "extracted" / phase
    mods_dir.mkdir(parents=True, exist_ok=True)

    if not zip_path.exists():
        summary["artifacts"] = "zip missing"
        return

    flat_zip = mods_dir / f"mods_{request_id}_{request_id}.zip"
    shutil.copyfile(zip_path, flat_zip)
    summary["zip"] = str(flat_zip.relative_to(_TARGET))

    if extracted_dir.exists():
        shutil.rmtree(extracted_dir)
    extracted_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(extracted_dir)
    summary["files"] = sorted(
        str(p.relative_to(extracted_dir)).replace("\\", "/")
        for p in extracted_dir.rglob("*") if p.is_file()
    )


def static_validate(summary: dict) -> list[str]:
    phase = summary["phase"]
    request_id = summary["request_id"]
    zip_path = _LOCAL_OUTPUT_DIR / "mods" / request_id / f"{request_id}.zip"
    if not zip_path.exists():
        return ["zip missing"]
    try:
        from tests.smapi_validate import validate_zip_contents
        return validate_zip_contents(zip_path)
    except Exception as exc:
        return [f"validator crashed: {type(exc).__name__}: {exc}"]


def write_readme(results: list[dict]) -> None:
    lines = [
        "# SDV Mod Generator - Demo Output (regenerated, fixed formats)",
        "",
        "Generated by `scripts/demo_generate.py` through the full LangGraph",
        "pipeline (`route -> generate -> T1 gate -> T2 gate -> package`) with no LLM",
        "keys configured (generators use deterministic fallback data).",
        "",
        f"- **Phases generated:** {len(results)}/10",
        f"- **Failed:** {sum(1 for r in results if r['status'] != 'done')}",
        "",
        "## What each mod contains",
        "",
    ]
    for r in results:
        lines.append(f"### {r['phase']} - status `{r['status']}`")
        lines.append(f"Prompt: `{r['prompt']}`")
        lines.append(
            f"T1 passed: `{r['t1_passed']}` - T2 score: `{r['t2_score']}` "
            f"(judge available: `{r['t2_available']}`)"
        )
        if r.get("errors"):
            lines.append("Errors:")
            for e in r["errors"]:
                lines.append(f"  - {e}")
        if r.get("files"):
            lines.append("Files (from the packaged zip):")
            for f in r["files"]:
                lines.append(f"  - {f}")
        if r.get("validator_errors"):
            lines.append("Static SMAPI validator:")
            for e in r["validator_errors"]:
                lines.append(f"  - {e}")
        lines.append("")

    lines.append("## Routing truth (what the router picked)")
    lines.append("")
    lines.append("| Prompt | Routed phase |")
    lines.append("|---|---|")
    for r in results:
        short = r["prompt"]
        if len(short) > 40:
            short = short[:40] + "..."
        lines.append(f"| `{short}` | `{r['phase']}` |")
    lines.append("")

    (_TARGET / "README.md").write_text("\n".join(lines), encoding="utf-8")


async def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate demo mods into mods/.test1")
    parser.add_argument("--phase", help="regenerate a single phase only")
    args = parser.parse_args()

    if args.phase:
        if args.phase not in {p[0] for p in DEMO_PROMPTS}:
            print(f"unknown phase: {args.phase}")
            sys.exit(1)
        prompts = [p for p in DEMO_PROMPTS if p[0] == args.phase]
    else:
        if _TARGET.exists():
            shutil.rmtree(_TARGET)
        prompts = DEMO_PROMPTS
    _TARGET.mkdir(parents=True, exist_ok=True)

    results: list[dict] = []
    for phase, prompt in prompts:
        print(f"==> generating {phase}")
        summary = await run_one(phase, prompt)
        print(f"    status={summary['status']} t1={summary['t1_passed']} "
              f"t2={summary['t2_score']}/{summary['t2_available']} "
              f"errors={summary['errors']}")
        copy_artifact(summary)
        summary["validator_errors"] = static_validate(summary)
        print(f"    validator_errors={summary['validator_errors']}")
        results.append(summary)

    if not args.phase:
        write_readme(results)

    shutil.rmtree(_LOCAL_OUTPUT_DIR, ignore_errors=True)

    print("\nSummary:")
    for r in results:
        print(f"  {r['phase']:20s} status={r['status']:6s} "
              f"t1={r['t1_passed']!s:5s} validator={len(r.get('validator_errors', []))} errors")
    print(f"\nOutput: {_TARGET}")


if __name__ == "__main__":
    asyncio.run(main())
